internal/spicedbx/schema.go
The tenant definition in the authzed schema had issues. Mainly, the
relationships referring to the roles were lacking prefixes. This fixes
that.
Closes: #22
Signed-off-by: Juan Antonio Osorio <juan.osoriorobles@eu.equinix.com>
=> Add missing prefix in schema

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml
This PR adds the `sshd` feature to the permissions-api dev container, allowing users to access it through SSH rather than `docker exec` or similar tools.
=> Add sshd feature and SSH support to dev container

pkg/client/v1/auth.go
A recent PR (https://github.com/infratographer/permissions-api/pull/47)
simplified the API endpoints and schema. This reflects the change in the
client by removing the API calls that are no longer applicable.
This also removes the explicit setting of the token in favor of using a
ready-to-go http.Client instance such as the one that
https://pkg.go.dev/golang.org/x/oauth2#section-readme may provide.
Signed-off-by: Juan Antonio Osorio <juan.osoriorobles@eu.equinix.com>
=> Remove invalid API calls from client

.devcontainer/Dockerfile
When using the devcontainer CLI to create a dev container, mounting ~/.ssh/authorized_keys from the host creates a directory owned by root, which causes failures when updating ~/.ssh/known_hosts as the vscode user. This PR adds this directory to the dev container so ~/.ssh/known_hosts works as expected.
=> Create ~/.ssh for vscode user

internal/query/tenants.go, internal/query/tenants_test.go, internal/spicedbx/schema.go
To make it easier to reason around what exactly is needed for authorization, and reduce the implicit coupling of services for getting resource information, this PR removes load balancers as a resource type in permissions-api.
=> Simplify schema to only be subjects, roles and tenants

.devcontainer/docker-compose.yml, cmd/server.go, go.mod, go.sum, internal/api/auth.go, internal/api/permissions.go, internal/api/resources.go, internal/api/router.go, internal/config/config.go, internal/query/tenants.go, internal/query/tenants_test.go, permission-api.example.yaml, pkg/pubsubx/worker.go
The current implementation of authentication in permissions-api expects a URN in the bearer token instead of a JWT. This PR updates permissions-api's API server to use JWT validation from [`ginjwt`][ginjwt] and URN parsing from [`urnx`][urnx] for more robust and secure authentication of clients making API requests.
Additionally, to make local development easier, a [mock-oauth2-server][mock-oauth2-server] service has been added to the Compose file. This service can be used to get JWT access tokens that permissions-api can be configured to accept instead of using an external identity provider or other authorization server.
[ginjwt]: https://pkg.go.dev/go.hollow.sh/toolbox@v0.5.1/ginjwt
[urnx]: https://pkg.go.dev/go.infratographer.com/x@v0.0.3/urnx
[mock-oauth2-server]: …
=> Authenticate API requests

README.md, internal/api/permissions.go, internal/api/resources.go, internal/api/router.go, internal/query/errors.go, internal/query/tenants.go, internal/query/tenants_test.go, pkg/client/v1/auth.go, pkg/client/v1/errors.go
This adds an initial README that describes the concepts that Permissions
API will cover. This allows us to have more consistent conversations in
the future about functionality and logic within the project.
This also persists the concepts and replaces the relevant wording in
functions and variables throughout the repository.
Note that the worker has not yet been touched, as we need to revisit how
that piece will work.
Signed-off-by: Juan Antonio Osorio <juan.osoriorobles@eu.equinix.com>
=> Add README with initial concepts and persist them throughout the repo

pkg/client/v1/auth.go
This allows us to have less dependencies for the client which makes it
easier to import as a krakend plugin.
Signed-off-by: Juan Antonio Osorio <juan.osoriorobles@eu.equinix.com>
=> client: Remove dependency to versionx

.golangci.yaml, cmd/doc.go, cmd/root.go, cmd/schema.go, cmd/server.go, internal/api/auth.go, internal/api/pagination.go, internal/api/response.go, internal/api/router.go, internal/config/config.go, internal/query/doc.go, internal/query/tenants.go, internal/spicedbx/client.go, internal/spicedbx/doc.go, internal/spicedbx/errors.go, internal/spicedbx/schema.go, internal/types/types.go, pkg/client/v1/auth.go, pkg/client/v1/errors.go
This adds the linter config we've been using in other projects. It also should fix all of the issues it found in the existing codebase.
=> Add linter config and fix linter issues

.github/workflows/image-build.yaml, .github/workflows/test.yaml
The trivy-action action removed the security-checks option in favor of the scanners option recently. This PR updates the existing image scanning action to use the right option and also adds image scanning to the test action.
=> Use scanners option for Trivy, add Trivy to test action

.devcontainer/Dockerfile, .github/workflows/image-build.yaml, .github/workflows/security.yaml, .github/workflows/test.yaml
The current image scanning workflow leads to Trivy scans being run twice because the test action is run on both PRs and pushes to main. To rectify this, a new security action has been added in this PR that only runs on PRs to scan both the permissions-api Git repository and Docker image. Additionally, repo scanning has been added to the image-build action and a typo in the image tag to be scanned has been fixed.
=> Use Trivy more effectively

internal/api/permissions.go, pkg/client/v1/auth.go
The provided client package was not using the correct authorization HTTP resource. This commit fixes that, and also removes tenant as a query param because we no longer need it to make authorization decisions.
=> Fix client code and use resource-level authorization

internal/query/tenants.go, internal/spicedbx/schema.go, internal/spicedbx/schema_test.go, internal/types/types.go
permissions-api does not currently define actions on roles or tenants, such as `tenant_get` or `role_list`, or distinguish between actions on a resource and actions on its tenant context. This PR addresses these issues by:
* Adding hardcoded actions for tenants and roles
* Adding `Actions` as an additional field on `ResourceType`, allowing for distinguishing between actions like "get" and "list"
Additionally, this PR fixes a bug when listing resource roles.
=> Better actions

docs/resource_management.md
permissions-api does not currently have a defined method for consuming resource lifecycle events from other services. This PR adds a document describing how it should work (but not necessarily the implementation).
=> Add document describing resource management

docs/resource_management.md
"additional_subjects" and "fields" serve related, but slightly different purposes in pubsubx. This PR updates the resource management design for permissions-api to use "fields" as the source of relationships to persist for resources rather than "additional_subjects", and additionally updates some ambiguous language.
=> Update resource management design to use fields for relationships

.devcontainer/.env, .devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .devcontainer/nats/nats-server.conf, .devcontainer/scripts/nats_init.sh, .gitignore, Makefile, cmd/root.go, cmd/worker.go, go.mod, go.sum, internal/api/router.go, internal/config/config.go, internal/pubsub/config.go, internal/pubsub/doc.go, internal/pubsub/subscriber.go, internal/pubsub/subscriber_test.go, internal/query/mock/doc.go, internal/query/mock/mock.go, internal/query/service.go, internal/query/tenants.go, internal/query/tenants_test.go, internal/testingx/testing.go
All resource lifecycle events are expected to flow to permissions-api through NATS. This PR introduces a NATS JetStream consumer based on a prior implementation of NATS worker logic in permissions-api that listens for events on resource types.
Additionally, this commit adds NATS-specific development tooling and updates the Makefile to perform some of the tool fetching/building logic that was previously in the dev container Dockerfile to reduce build times in CI.
[rm-doc]: https://github.com/infratographer/permissions-api/blob/11259e74d320bf8f8030133244160fe0db21e34b/docs/resource_management.md
=> Add NATS consumer for resource lifecycle events

chart/permissions-api/templates/serviceMonitor.yaml
Correct bad copy paste fail copying the incorrect port name.
=> correct service monitor port name

README.md
The README previously referred to the old API route, /has, for permissions checks. This commit updates it to refer to the current route, /allow.
=> Update README to refer to correct permissions check route

LICENSE, openapi-v1.yaml
The license used by Infratographer was changed from Apache 2.0 to the Elastic License v2.0 as a method to help protect the Infratographer project from non-intended use cases. With this change we have heard feedback from the community that this change isn't something that is desired. Based on this feedback we have decided to return to the original Apache 2.0 license.
=> Update License to Apache2.0

internal/iapl/default.go, internal/query/relations.go, internal/query/relations_test.go
Previously we were checking if the destination resource had a relation
rather than the targeted resource having a relation to the destination.
This resulted in the following not working:
```yaml
resourcetypes:
- name: folder
relationships:
- relation: parent
targettypenames:
- folder
- name: file
relationships:
- relation: parent
targettypenames:
- folder
```
When creating a relationship previously, relating a folder to a parent
folder would work since they happen to have the same resource type.
However relating a file to a parent folder would fail due to us checking
if folder has a parent relationship type name for file.
=> Fix relation validation

chart/permissions-api/templates/_helpers.tpl, chart/permissions-api/templates/deployment-server.yaml, chart/permissions-api/templates/deployment-worker.yaml
The worker was missing attaching the credsSecretName volume to the pod. This adds that.
=> worker volumes also need events volume support

chart/permissions-api/templates/deployment-worker.yaml, cmd/worker.go, internal/pubsub/subscriber.go, internal/pubsub/subscriber_test.go, internal/query/errors.go, internal/query/mock/mock.go, internal/query/relations.go, internal/query/relations_test.go, internal/query/service.go, policy.example.yaml
We were improperly building relationships setting the relation to the type of resource rather than the actual relation it had.
This now finds all the relations which are supported by the two resources and creates the appropriate relationships.
=> Correct event relationships

cmd/root.go, cmd/worker.go, internal/spicedbx/client.go
Adds http server for worker so the chart can properly run health checks.
Additionally updates the health check for spicedb to read the schema for it's health check.
=> add worker http server for health checks

chart/permissions-api/templates/deployment-server.yaml, chart/permissions-api/templates/deployment-worker.yaml
otelx uses "otlpgrpc" as the value for gRPC-based OTLP tracing, not "otlp". This PR fixes the Helm templates for permissions-api to use the correct value.
=> Check for otlpgrpc as tracing provider instead of otlp

go.mod, go.sum, pkg/permissions/permissions.go
The permissions-api client does not currently have OpenTelemetry support. This PR updates the permissions package to instrument the Permissions object, as well as add otelhttp support to enable context propagation from consuming services to permissions-api.
=> Add OpenTelemetry instrumentation to permissions-api client

internal/api/permissions.go, internal/query/mock/mock.go, internal/query/relations.go, internal/query/relations_test.go, internal/query/service.go
spicedb has caching, this ensures that checks, check the latest state.
=> ensure permissions checks are fully consistent

internal/api/roles.go, internal/api/router.go, internal/api/types.go, internal/query/errors.go, internal/query/mock/mock.go, internal/query/relations.go, internal/query/relations_test.go, internal/query/service.go
Adds endpoints to retrieve a role as well as retrieve a roles resource assignment.
=> Get role resources

chart/permissions-api/templates/deployment-worker.yaml, chart/permissions-api/values.yaml, cmd/worker.go, go.mod, go.sum, internal/api/relationships.go, internal/config/config.go, internal/pubsub/subscriber.go, internal/pubsub/subscriber_test.go, internal/query/mock/mock.go, internal/query/relations.go, internal/query/relations_test.go, internal/query/service.go, pkg/permissions/config.go, pkg/permissions/mockpermissions/permissions.go, pkg/permissions/mockpermissions/permissions_test.go, pkg/permissions/options.go, pkg/permissions/permissions.go, pkg/permissions/relationships.go, pkg/permissions/relationships_test.go
Updates to use the new [x/events](https://github.com/infratographer/x/pull/130) events package which removes the watermill format as well as implements the new AuthRelationshipRequest and Response events.
=> update to use new events handling

chart/permissions-api/templates/_helpers.tpl, chart/permissions-api/templates/config-server.yaml, chart/permissions-api/templates/config-worker.yaml, chart/permissions-api/templates/deployment-server.yaml, chart/permissions-api/templates/deployment-worker.yaml
After updating event topics to be pulled from the config file, viper doesn't handle environment slices automatically so instead it stores a single string with all topics.
Changing to using a config file simplifies config changes and ensures the correct values are read.
=> move chart to using a config file instead of env

chart/permissions-api/templates/deployment-worker.yaml, chart/permissions-api/values.yaml
This PR makes the worker image for permissions-api configurable separately from the API image.
=> Make worker image configurable

.github/workflows/test.yaml
It appears that newer Ubuntu runners check out code as UID 1001, which breaks CI as the default `vscode` user in dev containers is UID 1000 (see https://github.com/devcontainers/ci/issues/257). This PR addresses that issue by explicitly running `sudo chown` to make the `vscode` user own `/workspace`.
=> Explicitly set ownership of /workspace in CI runs

cmd/createrole.go, internal/api/permissions.go, internal/api/roles.go, internal/api/router.go, permissions-api.example.yaml, policy.example.yaml
This PR adds permissions checks for role management CRUD operations in the permissions-api API.
Because permissions checks are baked into the API (i.e., they cannot and should not be disabled), this PR also adds a command, `create-role`, which can be used to bootstrap the creation of roles that can allow a subject to create other roles. The conditions for actions like `role_create` are deliberately left out of permissions-api to allow operators to define their own policies.
=> Role permissions checks

internal/api/assignments.go
This commit adds permissions checks to role assignments. Rather than define new actions here, we just use the already-defined actions for role management.
=> Add permissions checks to assignments

internal/api/relationships.go, internal/api/router.go, internal/api/types.go
NATS is the interface being used for relationship management now. relationshipCreate and relationshipDelete are redundant and also hard to make secure, since this part of the API is more of a management of the SpiceDB graph itself instead of management of resources that are on the SpiceDB graph. This commit removes both of them and their respective API routes.
=> Remove relationship create/delete handlers

cmd/schema_mermaid.go
This PR includes some light fixes to the mermaid template we have for generating graphs based on the schema.
It looks like this when rendered with the default (test) policy:
```mermaid
erDiagram
role {
id_prefix permrol
}
role }o--o{ subject : subject
user {
id_prefix idntusr
}
client {
id_prefix idntcli
}
tenant {
id_prefix tnntten
}
tenant }o--o{ tenant : parent
loadbalancer {
id_prefix loadbal
action loadbalancer_get
action loadbalancer_update
action loadbalancer_delete
owner_action loadbalancer_get
owner_action loadbalancer_update
owner_action loadbalancer_delete
}
loadbalancer }o--o{ resourceowner : owner
subject {
}
subject ||--|| user : alias
subject ||--|| client : alias
resourceowner {
action loadbalancer_create
action loadbalancer_get
action loadbalancer_update
action …
```
=> Update mermaid template

pkg/permissions/config.go
=> Update config.go to fix ignoreNoResponders

renovate.json
This ensures all otel packages are updates in the same pr which depend on each other.
Previously otel updates would frequently result in broken builds as many of the packages would get updated in separate renovate prs but depend on new updated packages. This should ensure they are all updated together.
=> update renovate to update all otel packages in a single pr

cmd/createrole.go, internal/api/assignments.go, internal/api/relationships.go, internal/api/roles.go, internal/pubsub/subscriber.go, internal/pubsub/subscriber_test.go, internal/query/mock/mock.go, internal/query/relations.go, internal/query/relations_test.go, internal/query/service.go
This switches us to fully consistent reads of relationships which ensures after any action has been taken a subsequent read request will return the most up to date information.
This resolves an issue seen when directly after creating a role, a client may fail to assign a subject to the newly created role.
=> use full consistent reads

chart/permissions-api/templates/_helpers.tpl, chart/permissions-api/templates/config-server.yaml, chart/permissions-api/values.yaml, cmd/createrole.go, cmd/kv.go, cmd/server.go, cmd/worker.go, go.mod, internal/config/config.go, internal/query/relations.go, internal/query/relations_test.go, internal/query/service.go, internal/query/zedtokens.go, internal/query/zedtokens_test.go, permissions-api.example.yaml
Using full consistency when doing permissions checks is slow. In general, this is addressed by using ZedTokens to indicate minimum bounds on freshness when looking up cached data. Something has to keep track of those tokens, either on the client side or server-side.
This PR introduces worker caching of ZedTokens for resources on updates to relationships and updates the query engine to use those tokens when performing permissions checks. When a worker updates a relationship, it persists the ZedToken for all resources directly affected by that update to a NATS KV bucket. NATS KV writes are immediately consistent, so the new ZedToken for that resource is available to all consumers, including permissions-api API frontends. When the query engine performs a permissions check, it checks to see …
=> Cache ZedTokens for resources using NATS

pkg/permissions/config.go, pkg/permissions/permissions.go, pkg/permissions/permissions_test.go
Easily permit permission checks when the permission library doesn't have a proper url configured.
This simplifies local development for service which implement permissions checks allowing them to skip calling out to a permissions service while developing locally by simply enabling `AllowUnconfiguredChecks`.
=> permit unconfigured permission checks

pkg/permissions/errors.go, pkg/permissions/permissions.go
Services wanting to check if the error returned was an auth error or some other error could get a number of auth related errors.
This wraps the permissions and auth errors into easily comparable root errors for easier checks.
Additionally this corrects the incorrectly returned echo errors which were missing for PermissionDenied errors which resulted in 500 errors.
=> wrap errors for easier handling in external services

cmd/root.go
Should have been included in #231 - a part of policy directory updates.
=> Update root cmd & viper binding for policydir flag

.gitignore, cmd/schema_mermaid.go, docs/iapl.md, docs/rbac.md, internal/iapl/default.go, internal/iapl/errors.go, internal/iapl/policy.go, internal/iapl/policy_test.go, internal/iapl/rbac.go, internal/query/relations.go, internal/query/relations_test.go, internal/query/service.go, internal/spicedbx/schema.go, internal/spicedbx/schema_test.go, internal/types/types.go, policies/policy.example.yaml
In order to separate roles from bindings in permissions-api, we need to update the generated SpiceDB schema with a definition for bindings and permissions that check both direct assignment to roles and bindings (i.e., we don’t want to break existing assignments). The scope of this task is to update permissions-api to generate a SpiceDB schema with a binding definition that associates a subject (i.e., any principal) to a role.
see [this doc](https://github.com/infratographer/permissions-api/blob/41bcf2e66f9e8de28329580fd0c987cf1ae06cd6/docs/rbac.md) for more
=> role-binding v2 schema and IAPL

Makefile, cmd/server.go, internal/api/assignments.go, internal/api/assignments_test.go, internal/api/errors.go, internal/api/response.go, internal/api/roles.go, internal/api/roles_test.go, internal/api/roles_v2.go, internal/api/router.go, internal/api/router_test.go, internal/api/types.go, internal/iapl/policy.go, internal/iapl/rbac.go, internal/query/default_test.go, internal/query/errors.go, internal/query/mock/mock.go, internal/query/relations.go, internal/query/relations_test.go, internal/query/roles.go, internal/query/roles_v2.go, internal/query/roles_v2_test.go, internal/query/service.go, internal/query/zedtokens_test.go, internal/storage/roles.go
continue work on https://github.com/infratographer/permissions-api/pull/219
The API should be updated to use them in place of direct role assignments. The scope of this task is to make the following API changes:
=> RBAC V2 - Roles APIs

cmd/createrole.go, internal/api/rolebindings.go, internal/api/roles_v2.go, internal/api/router.go, internal/api/types.go, internal/query/default_test.go, internal/query/errors.go, internal/query/example_policy_test.go, internal/query/mock/mock.go, internal/query/relations.go, internal/query/relations_test.go, internal/query/rolebindings.go, internal/query/rolebindings_test.go, internal/query/roles_v2.go, internal/query/roles_v2_test.go, internal/query/service.go, internal/storage/errors.go, internal/storage/migrations/20240425000000_role_bindings.sql, internal/storage/rolebinding.go, internal/storage/rolebinding_test.go, internal/storage/roles.go, internal/storage/storage.go, internal/types/types.go, openapi-v2.yaml, policies/policy.example.yaml
continue work on #245 
The API should be updated to use them in place of direct role assignments. The scope of this task is to make the following API changes:
Roles
Create appropriate action relationships from the roles to subject:* type relationships rather than relationships from other resources to the roles
Assignments
Create a binding when creating an assignment rather than creating a direct membership to the role
List both bindings and direct memberships when listing assignments (and show an ID for bindings)
Delete both bindings and direct memberships when deleting assignments
Check permissions based on binding_{create,get,update,delete} actions rather than role-specific actions
See [this OpenAPI specs](https://github.com/infratographer/permissions-api/blob/cb0934db964f2d3638810ed6083 …
=> RBAC v2 role bindings

internal/iapl/policy.go
Traversing the policy directory recursively in Kubernetes results in duplicate policies being read, as Kubernetes ConfigMaps store all files as symlinks to a `..data` directory inside the actual volume.
To mitigate this issue, this PR prevents hidden directories below the top level directory from being visited.
=> Do not traverse hidden policy directories

cmd/createrole.go, cmd/server.go, go.mod, go.sum, internal/query/mock/mock.go, internal/query/relations.go, internal/query/relations_test.go, internal/query/service.go, internal/query/zedtokens.go, internal/query/zedtokens_test.go
This PR updates the query engine to watch KV updates rather than reach out to the bucket for every permissions check. This is primarily done to improve performance at the expense of some consistency (i.e., the time it takes for a permissions-api server to receive an update).
=> Watch for KV updates instead of reaching out for tokens

internal/api/rolebindings.go, openapi-v2.yaml
When creating a rolebinding, the API should return `201` upon successful requests
=> Use HTTP 201 for role-binding creates

internal/iapl/policy.go, internal/iapl/policy_test.go
Add `idprefix` validation on IAPL validate
=> Add idprefix validation

internal/iapl/policy.go
Errors previously only included their index to the particular portion which resulted in the error.
```
actionBindings: 92: conditions: 1: owner: unknown relation
```
This pr updates it to also include some details about the particular entry that resulted in the error to make it easier to locate the actual issue.
```
actionBindings: 318 (account:user): conditions: 1: owner: unknown relation
```
=> ensure validation errors include names for better context

cmd/schema_mermaid.go
This better represents the action and action relationship lookups in mermaid graphs.
Before:
```mermaid
erDiagram
rolebinding }o--o{ rolev2 : role
rolebinding }o--o{ user : subject
rolebinding }o--o{ client : subject
rolebinding }o--o{ group : subject
user {
id_prefix idntusr
}
client {
id_prefix idntclt
}
role {
id_prefix permrol
}
role }o--o{ subject: subject
tenant {
id_prefix tnntten
}
tenant }o--o{ tenant: parent
tenant }o--o{ rolebinding: grant
group {
id_prefix idntgrp
subgroup_action member
}
group }o--o{ rolebinding: grant
group }o--o{ group: parent
group }o--o{ tenant: parent
group }o--o{ user: direct_member
group }o--o{ client: direct_member
group }o--o{ group: subgroup
loadbalancer {
id_prefix loadbal
action loadbalancer_get
action loadbalancer_update
action …
```
=> better represent structure in mermaid graph

.golangci.yaml, Makefile
Updates golangci-lint to v1.59.1 along with it's config file.
=> update golangci-lint to v1.59.1

internal/query/relations.go
Roles created with no actions are not able to be retrieved or deleted in permissions-api as a result of fetching the role's resource ID from SpiceDB rather than CRDB. This PR updates the storage engine to use CRDB instead.
=> Use CRDB instead of SpiceDB for getting role resource

internal/query/relations.go, internal/query/relations_test.go, internal/query/roles_v2.go, internal/query/roles_v2_test.go, internal/storage/errors.go
Prior implementations of the query engine fetched role information such as the owning resource ID directly from SpiceDB, as it was the only data store available. With the introduction of CRDB, that is no longer the case and the CRDB SQL table should be considered the authoritative source of most role data. This PR updates the query engine to fetch role resource owner ID and other data from the SQL DB whenever possible, getting rid of some obscure failure modes that occur when a role has no associated actions.
=> Simplify role fetching logic in query engine

internal/api/router.go, internal/api/router_test.go
Errors may be wrapped by a specific echo http error by a handler.
In some cases (such as canceled context) this might report as a 500
error, however this error might've been triggered by the requestor.
To simplify handling this scenario, we will unwrap the http error,
preserving the original message only if the error is a context canceled
error and the request context has been canceled.
=> properly handle echo http wrapped errors

internal/iapl/policy.go, internal/iapl/rbac.go, internal/query/default_test.go, policies/policy.example.yaml
By default when specifying `InheritPermissionsFrom` on resource type's RoleBindingV2 all actions were being inherited rather than only inheriting RBAC v2 actions.
This change reduces the default inheritance to only the RBAC v2 actions but setting `InheritAllActions` to `true` will automatically include inheritance for all configured actions on that resource type.
=> Don't defaulty inherit all actions for role binding v2

cmd/createrole.go, internal/api/rolebindings.go, internal/api/roles.go, internal/api/roles_v2.go, internal/api/types.go, internal/query/example_policy_test.go, internal/query/mock/mock.go, internal/query/relations.go, internal/query/relations_test.go, internal/query/rolebindings.go, internal/query/rolebindings_test.go, internal/query/roles_v2.go, internal/query/roles_v2_test.go, internal/query/service.go, internal/storage/migrations/20241001000000_manager_fields.sql, internal/storage/rolebinding.go, internal/storage/rolebinding_test.go, internal/storage/roles.go, internal/storage/roles_test.go, internal/types/types.go, openapi-v2.yaml
This adds a manager field to roles and role bindings allowing services to mark the manager of a specific role / role binding.
This allows the managing service to easily filter out unmanaged roles / role bindings which it does not own which allows for cleaner logic for reconciling roles/role bindings.
Both roles and role binding create requests can provide an optional `manager` field and role / role binding list endpoints can now be provided an optional `manager` query value.
=> add manager field to simplify multi service management

internal/pubsub/subscriber.go, internal/query/relations.go
This adds more details to the pubsub.receive trace. Errors are recorded. If a downstream error occurs the trace is set to the error status.
This will allow us to better know which events are having issues.
=> add details to pubsub trace

.golangci.yaml, go.mod, go.sum, pkg/permissions/config.go, pkg/permissions/internal/selecthost/doc.go, pkg/permissions/internal/selecthost/helpers.go, pkg/permissions/internal/selecthost/helpers_test.go, pkg/permissions/internal/selecthost/host.go, pkg/permissions/internal/selecthost/host_test.go, pkg/permissions/internal/selecthost/http.go, pkg/permissions/internal/selecthost/http_test.go, pkg/permissions/internal/selecthost/options.go, pkg/permissions/internal/selecthost/selector.go, pkg/permissions/internal/selecthost/selector_test.go, pkg/permissions/logger.go, pkg/permissions/options.go, pkg/permissions/permissions.go
This copies the selecthost package from iam-runtime-infratographer which adds SRV lookup for the configured URL.
Additionally, similar to iam-runtime-infratographer, the http client has been replaced with a retryable http client to allow for graceful failover when a host has become unreachable.
=> add SRV support to permissions package
